stages:
  - check
  - build
  - deploy dev
  - deploy prod

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_SHORT_SHA

go format check:
  image: golang:1.14
  stage: check
  script:
    - diff -u <(echo -n) <(gofmt -d ./)

editorconfig check:
  image: mstruebing/editorconfig-checker
  stage: check
  script:
    - ec

.build: &build
  stage: build
  image: golang:1.14
  script:
    - go build -o hello .
  artifacts:
    paths:
      - hello

build linux:
  <<: *build

build mac:
  <<: *build
  variables:
    GOOS: darwin

build windows:
  <<: *build
  variables:
    GOOS: windows

build docker:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE
