stages:
  - check
  - build
  - deploy dev
  - deploy prod

go format check:
  image: golang:1.14
  stage: check
  script:
    - diff -u <(echo -n) <(gofmt -d ./)

editorconfig check:
  image: mstruebing/editorconfig-checker
  stage: check
  script:
    - ec

build linux:
  image: golang:1.14
  script:
    - go build . -o hello
  artifacts:
    paths:
      - hello
